### ISSUE TITLE
Sample applications don't build with latest version of Simmy package

### ISSUE THREAD

**Issue by benpeart** [Polly-Contrib/Polly.Contrib.SimmyDemo_WebApi#7]
After updating the Polly.Contrib.Simmy package to the latest version (0.2.0), the sample no longer builds but fails with:

Chaos/SimmyExtensions.cs(38,46): error CS0029: Cannot implicitly convert type 'System.Threading.Tasks.Task<System.Exception>' to 'System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage>' [/mnt/c/src/Polly.Contrib.SimmyDemo_WebApi/SimmyDemo_WebApi/SimmyDemo_WebApi.csproj]

**Comment by reisenberger** [comment]
Thanks @benpeart .  I am away.  /cc @vany0114 just in case he can help with this.

**Comment by vany0114** [comment]
@benpeart sorry for the delay, I just put a PR #8 to fix the example, thanks for the heads up!

**Comment by reisenberger** [comment]
Thanks @benpeart for your interest in Simmy (love to hear any more about what you are doing with it), and for raising this.  Fixed by #8 thanks to @vany0114 !
